### ISSUE TITLE
Any plan for linter, formatter and more tests?

### ISSUE THREAD

**Issue by hitochan777** [weseek/crowi-plus#291]
Currently it seems like linters (e.g. ESLint), formatter (e.g. prettier) are not applied to the code.
Also, there are some tests, but they do not cover most of the code, as far as I can see.

Do you have any plan to

1. apply a linter
2. apply a formatter
3. add more tests?

If you plan to maintain this repo for a long time, I guess these should be recommended.
If you are up to this, I would love to contribute. Thanks in advance.

**Comment by yuki-takei** [comment]
@hitochan777 
> If you plan to maintain this repo for a long time, I guess these should be recommended.
It's exactly as you said.

1,2
I have not adopted these tools until now, but I will put it in the near future.
However, we might have to avoid automatic applying formatter because many unexpected modifications will be included in a PR at this time.

3,
We agree that tests are very important. But we can't take time for it at this time.
It will be great help if you contribute about tests.

**Comment by hitochan777** [comment]
@yuki-takei ok, thanks. I will work on adding more tests.

**Comment by yuki-takei** [comment]
@hitochan777 I applied eslint to master branch. 
I will gradually apply formatter or linter at test.
Anyway, I close this.
